"""One-off generator for app/native/src/mx_iq_grids.h - the grid-based I-quant lookup tables

(IQ1_S/IQ1_M/IQ2_XXS/IQ2_XS/IQ2_S/IQ3_XXS/IQ3_S), as static C arrays for the native kernels.

Reads the same already-checked-in, already-extracted-verbatim .npy files
`app/gguf/dequant/iq_grids.py` loads at runtime (see that module's own docstring: extracted from
ggml's real source by scripts/extract_iq_grids.py, not hand-transcribed) - never re-derives the
values, just re-encodes the same real data as C source instead of re-reading .npy files at
process startup. Kept in the repo (like extract_iq_grids.py itself) for a future ggml version
bump; re-run and commit the result if app/gguf/dequant/data/*.npy ever changes.

    .venv/bin/python -m scripts.generate_iq_grids_c
"""

import numpy as np

from app.gguf.dequant import iq_grids

_OUTPUT = "app/native/src/mx_iq_grids.h"


def _c_array(name: str, ctype: str, values: np.ndarray) -> str:
    flat = values.reshape(-1)
    body = ", ".join(str(int(v)) for v in flat)
    return f"static const {ctype} {name}[{flat.size}] = {{{body}}};\n"


def main() -> None:
    lines = [
        "/*\n",
        " * Generated by scripts/generate_iq_grids_c.py - do not hand-edit.\n",
        " * Real ggml grid/sign tables, extracted verbatim (see app/gguf/dequant/iq_grids.py's\n",
        " * own docstring) - re-run the generator if app/gguf/dequant/data/*.npy ever changes.\n",
        " */\n",
        "#ifndef MX_IQ_GRIDS_H\n",
        "#define MX_IQ_GRIDS_H\n\n",
        "#include <stdint.h>\n\n",
        _c_array("MX_KMASK_IQ2XS", "uint8_t", iq_grids.kmask_iq2xs()),
        _c_array("MX_KSIGNS_IQ2XS", "uint8_t", iq_grids.ksigns_iq2xs()),
        _c_array("MX_IQ2XXS_GRID", "int8_t", iq_grids.iq2xxs_grid_i8()),
        _c_array("MX_IQ2XS_GRID", "int8_t", iq_grids.iq2xs_grid_i8()),
        _c_array("MX_IQ2S_GRID", "int8_t", iq_grids.iq2s_grid_i8()),
        _c_array("MX_IQ3XXS_GRID", "int8_t", iq_grids.iq3xxs_grid_i8()),
        _c_array("MX_IQ3S_GRID", "int8_t", iq_grids.iq3s_grid_i8()),
        _c_array("MX_IQ1S_GRID", "int8_t", iq_grids.iq1s_grid_i8()),
        "\n#endif\n",
    ]
    with open(_OUTPUT, "w") as f:
        f.writelines(lines)
    print(f"wrote {_OUTPUT}")


if __name__ == "__main__":
    main()
